//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_CRDT
    {
        public int CustomerCreditId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<decimal> SettledAmount { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<bool> SettledInd { get; set; }
    
        public virtual CUST_DATA CUST_DATA { get; set; }
    }
}
