//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CUST_BILL
    {
        public int BillId { get; set; }
        [Required]
        public int CustomerId { get; set; }

        public System.DateTime PaymentDate { get; set; }
        [Required]
        public decimal DueAmount { get; set; }
        [Required]

        [Range(0, double.MaxValue, ErrorMessage = "Value must be a positive number.")]
        public decimal PaidAmount { get; set; }
        public decimal RemainingAmount { get; set; }
        public Nullable<decimal> PreviousCredit { get; set; }
    
        public virtual CUST_DATA CUST_DATA { get; set; }
    }
}
