//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CUST_DATA
    {
        public CUST_DATA()
        {
            this.JOBS = new HashSet<JOB>();
            this.CUST_BILL = new HashSet<CUST_BILL>();
            this.CUST_CRDT = new HashSet<CUST_CRDT>();
            this.DUES_ALRT = new HashSet<DUES_ALRT>();
            this.CUST_INVC = new HashSet<CUST_INVC>();
        }

        public int CustomerId { get; set; }
        [Required]
        public string CustomerName { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string ContactNo { get; set; }

        public string EmailAddress { get; set; }
        public string AccountRefNumber { get; set; }
        public Nullable<bool> HasAccount { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> HasContract { get; set; }
        public string ContactNo2 { get; set; }
        public string ContactNo3 { get; set; }
        public string ContactNo4 { get; set; }
        public string ContactNo5 { get; set; }
        public string PersonalAddress { get; set; }
        public bool RecieveNotifications { get; set; }

        public virtual ICollection<JOB> JOBS { get; set; }
        public virtual ICollection<CUST_BILL> CUST_BILL { get; set; }
        public virtual ICollection<CUST_CRDT> CUST_CRDT { get; set; }
        public virtual ICollection<DUES_ALRT> DUES_ALRT { get; set; }
        public virtual ICollection<CUST_INVC> CUST_INVC { get; set; }
    }
}
