//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_TRAN
    {
        public int TransactionId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<bool> SettledInd { get; set; }
    }
}
