//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_INVC
    {
        public CUST_INVC()
        {
            this.CUST_TRAN = new HashSet<CUST_TRAN>();
        }
    
        public int InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string InvoiceStatus { get; set; }
        public Nullable<int> InvoicePaymentMode { get; set; }
        public Nullable<int> JobId { get; set; }
        public string ReportMarkup { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual INVC_PYMT_MODE INVC_PYMT_MODE { get; set; }
        public virtual ICollection<CUST_TRAN> CUST_TRAN { get; set; }
        public virtual JOB JOB { get; set; }
        public virtual CUST_DATA CUST_DATA { get; set; }
    }
}
