//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DALY_PRCL
    {
        public int DailyParcelId { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<System.DateTime> TimeOfDay { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual DALY_PRCL_MSTR DALY_PRCL_MSTR { get; set; }
    }
}
