//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRVR_TRAN
    {
        public int DriverTransId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<bool> SettledInd { get; set; }
    }
}
