//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DRVR_MSGS
    {
        public int MessageId { get; set; }
        public Nullable<int> DriverId { get; set; }
        [Required]
        public string Message { get; set; }
        public Nullable<bool> MessageReceivedInd { get; set; }
        public System.DateTime MessageDate { get; set; }
        public Nullable<bool> MessageReadInd { get; set; }
    
        public virtual DRVR_DATA DRVR_DATA { get; set; }
    }
}
