//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DRVR_DATA
    {
        public DRVR_DATA()
        {
            this.DRVR_MSGS = new HashSet<DRVR_MSGS>();
            this.JOBS = new HashSet<JOB>();
            this.JOBS_RESP = new HashSet<JOBS_RESP>();
            this.DRVR_TIME_SHET = new HashSet<DRVR_TIME_SHET>();
        }

        public int DriverId { get; set; }
        [Required]
        public string DriverName { get; set; }

        [Required]
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public string SecurityAnswer { get; set; }

        [Required]
        public string GcmId { get; set; }
        public bool IsActive { get; set; }

        [Required(ErrorMessage = "Driver contract number is required.")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{4})[-. ]?([0-9]{4})$", ErrorMessage = "Entered phone number is not valid.")]
        public string ContactNo { get; set; }

        [Required(ErrorMessage = "Commission is required for the driver.")]
        [Range(0, 100)]
        public Nullable<decimal> CommissionRate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public bool IsOnHourlyRate { get; set; }
    
        public virtual SCRT_QUES SCRT_QUES { get; set; }
        public virtual ICollection<DRVR_MSGS> DRVR_MSGS { get; set; }
        public virtual ICollection<JOB> JOBS { get; set; }
        public virtual ICollection<JOBS_RESP> JOBS_RESP { get; set; }
        public virtual ICollection<DRVR_TIME_SHET> DRVR_TIME_SHET { get; set; }
    }
}
