//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRVR_TIME_SHET
    {
        public int TimesheetId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> AmountEarned { get; set; }
        public bool SettledInd { get; set; }
        public bool IsLoggedIn { get; set; }
    
        public virtual DRVR_DATA DRVR_DATA { get; set; }
    }
}
