//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAL_ACNT
    {
        public int EmailAccountId { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public int EmailClient { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
    }
}
