//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBS_RESP
    {
        public int JobResponseId { get; set; }
        public int JobId { get; set; }
        public int DriverId { get; set; }
        public string ResponseCode { get; set; }
        public bool IsAssigned { get; set; }
        public System.DateTime ResponseTime { get; set; }
    
        public virtual DRVR_DATA DRVR_DATA { get; set; }
        public virtual JOB JOB { get; set; }
    }
}
