//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNDG_JOBS
    {
        public int JobId { get; set; }
        public string JobStatus { get; set; }
        public string PickupAddress { get; set; }
        public string DropAddress { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> JobDate { get; set; }
        public Nullable<bool> AccountPaymentInd { get; set; }
        public string ChargesDescription { get; set; }
        public Nullable<bool> LongDistanceInd { get; set; }
        public string DropoffContact { get; set; }
        public string DropAddress1 { get; set; }
        public string DropAddress2 { get; set; }
        public string DropAddress3 { get; set; }
        public string DropAddress4 { get; set; }
        public string TypeOfParcel { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string Reference { get; set; }
        public string HangfireId { get; set; }
        public Nullable<System.DateTime> ScheduledTime { get; set; }
    }
}
