//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class REQT_DRVR
    {
        public int DriverReqId { get; set; }
        [Required]
        public string DriverName { get; set; }
        [Required]
        public string LoginName { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string GcmId { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public string SecurityAnswer { get; set; }
        public string ContactNo { get; set; }
        public bool IsConverted { get; set; }
    }
}
