//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESN
    {
        public int SessionId { get; set; }
        public string SessionCode { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> SessionDate { get; set; }
    
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
