//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER
    {
        public SYS_USER()
        {
            this.SESNs = new HashSet<SESN>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public string SecurityAnswer { get; set; }
    
        public virtual SCRT_QUES SCRT_QUES { get; set; }
        public virtual ICollection<SESN> SESNs { get; set; }
    }
}
